services:
  api:
    container_name: menu-link-up
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=../../.local/local-secrets.json
    env_file:
      - .env.local
    ports:
      - 8080:8080
